// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPoEcawQirCgAPah89H_E5X8SDnOmFpQ',
    appId: '1:800048961892:web:2c6047d4ffb73350830271',
    messagingSenderId: '800048961892',
    projectId: 'einburgeringtest-2026',
    authDomain: 'einburgeringtest-2026.firebaseapp.com',
    storageBucket: 'einburgeringtest-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIcq40t7WN-QgMFy45ZhAM4o6Epc9Eys',
    appId: '1:800048961892:android:3fa23b018aa7a2d5830271',
    messagingSenderId: '800048961892',
    projectId: 'einburgeringtest-2026',
    storageBucket: 'einburgeringtest-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe174AS-K5VbijBziEiuTgKfKN2GUadZU',
    appId: '1:800048961892:ios:b8c37c0cb908e1d8830271',
    messagingSenderId: '800048961892',
    projectId: 'einburgeringtest-2026',
    storageBucket: 'einburgeringtest-2026.firebasestorage.app',
    androidClientId: '800048961892-aguuo7dm4arit7algch9he36ns28ismv.apps.googleusercontent.com',
    iosClientId: '800048961892-c1mt2i9crgst9pn60hiqb34qt6hh6k95.apps.googleusercontent.com',
    iosBundleId: 'com.example.einbuergerungstest2026',
  );

}