import 'dart:convert';
import 'dart:io';

void main() async {
  final Map<String, String> translations = {
    "1": "Soru, Almanya'da insanların neden hükümeti eleştirebildiğini sormaktadır. Doğru cevap 'burada ifade özgürlüğü geçerli olduğu için'dir.",
    "2": "Soru, ebeveynlerin çocuklarının 14 yaşına kadar hangi derse katılıp katılmayacağına karar verebileceğini sormaktadır. Doğru cevap 'Din dersi'dir.",
    "3": "Soru, 'Hukuk Devleti'nin ne anlama geldiğini sormaktadır. Doğru cevap 'Tüm vatandaşlar ve devlet yasalara uymak zorundadır' şeklindedir.",
    "4": "Soru, Almanya'da temel haklardan birini sormaktadır. Doğru cevap 'İfade Özgürlüğü'dür.",
    "5": "Soru, seçimlerin 'Özgür' olmasının ne anlama geldiğini sormaktadır. Doğru cevap 'Seçmenin etki altında kalmadan ve zorlanmadan oy verebilmesi'dir.",
    "6": "Soru, Alman Anayasası'nın adını sormaktadır. Doğru cevap 'Grundgesetz'tir.",
    "7": "Soru, Anayasa tarafından garanti edilen temel bir hakkı sormaktadır. Doğru cevap 'İnanç ve vicdan özgürlüğü'dür.",
    "8": "Soru, Anayasa'da yer almayan maddeyi sormaktadır. Doğru cevap 'Herkesin eşit paraya sahip olması'dır.",
    "9": "Soru, Almanya'da sadece yabancılar için geçerli olan temel hakkı sormaktadır. Doğru cevap 'İltica Hakkı'dır (Asyl).",
    "10": "Soru, hangisinin Anayasa ile uyumlu bir ceza olduğunu sormaktadır. Doğru cevap 'Para cezası'dır.",
    "11": "Soru, Federal Almanya Cumhuriyeti Anayasası'nın ismini sormaktadır. Doğru cevap 'Grundgesetz'tir.",
    "12": "Soru, Basın Özgürlüğü'nün kaldırılıp kaldırılamayacağını sormaktadır. Doğru cevap 'Hayır, çünkü o temel bir haktır' şeklindedir.",
    "13": "Soru, parlamentoda 'Muhalefet' kavramının ne anlama geldiğini sormaktadır. Doğru cevap 'Hükümete dahil olmayan tüm milletvekilleri'dir.",
    "14": "Soru, İfade Özgürlüğü'nün ne anlama geldiğini sormaktadır. Doğru cevap 'İnternette görüşümü belirtebilirim' seçeneğidir.",
    "15": "Soru, Anayasa'nın neyi yasakladığını sormaktadır. Doğru cevap 'Zorla çalıştırma'dır (Zwangsarbeit).",
    "16": "Soru, İfade Özgürlüğü'nün ne zaman sınırlandığını sormaktadır. Doğru cevap 'Yalan iddialar yayıldığında veya başkalarına hakaret edildiğinde'dir.",
    "17": "Soru, Alman yasalarının neyi yasakladığını sormaktadır. Doğru cevap 'Devletin vatandaşlara eşit davranmamasını'dır.",
    "18": "Soru, Anayasa'nın 1. Maddesi'nde garanti edilen hakkı sormaktadır. Doğru cevap 'İnsan onurunun dokunulmazlığı'dır.",
    "19": "Soru, 'Seyahat ve Yerleşme Özgürlüğü'nün (Freizügigkeit) ne anlama geldiğini sormaktadır. Doğru cevap 'Kişinin ikamet edeceği yeri kendisinin seçebilmesi'dir.",
    "20": "Soru, diktatörlük kurmayı hedefleyen bir partinin durumunu sormaktadır. Doğru cevap 'Anayasaya aykırıdır' (verfassungswidrig).",
    "21": "Soru, Federal Almanya Cumhuriyeti'nin armasını sormaktadır. Doğru cevap 'Kartal figürüdür' (Bild 1).",
    "22": "Soru, Almanya'nın devlet biçimini sormaktadır. Doğru cevap 'Cumhuriyet'tir.",
    "23": "Soru, Almanya'da çalışanların çoğunun statüsünü sormaktadır. Doğru cevap 'Bir firmada veya kurumda işçi/memur olarak çalışırlar' şeklindedir.",
    "24": "Soru, Almanya'nın kaç eyaletten oluştuğunu sormaktadır. Doğru cevap '16'dır.",
    "25": "Soru, hangisinin Almanya'nın bir eyaleti olmadığını sormaktadır. Doğru cevap 'Alsas-Loren'dir.",
    "26": "Soru, Almanya'nın nasıl bir devlet olduğunu sormaktadır. Doğru cevap 'Demokratik ve sosyal bir federal devlettir'.",
    "27": "Soru, Almanya'nın devlet yapısını sormaktadır. Doğru cevap 'Bir Federal Devlet'tir.",
    "28": "Soru, Federal Meclis milletvekillerini kimin seçtiğini sormaktadır. Doğru cevap 'Oy kullanma hakkına sahip halk'tır.",
    "29": "Soru, Federal Almanya Cumhuriyeti'nin armasındaki hayvanı sormaktadır. Doğru cevap 'Kartal'dır.",
    "30": "Soru, hangisinin demokrasinin bir özelliği olmadığını sormaktadır. Doğru cevap 'Basın Sansürü'dür.",
    "31": "Soru, hükümet kurmak için partilerin işbirliği yapmasına ne dendiğini sormaktadır. Doğru cevap 'Koalisyon'dur.",
    "32": "Soru, hangisinin devletin temel güçlerinden biri olmadığını sormaktadır. Doğru cevap 'Basın'dır.",
    "33": "Soru, Almanya'da devlet ve din ilişkisini sormaktadır. Doğru cevap 'Devlet ve dini cemaatler birbirinden ayrıdır' şeklindedir.",
    "34": "Soru, Almanya'nın yönetim şekli olmayanı sormaktadır. Doğru cevap 'Monarşi'dir.",
    "35": "Soru, devletin sosyal sigorta sistemini nasıl finanse ettiğini sormaktadır. Doğru cevap 'Sosyal kesintilerle'dir.",
    "36": "Soru, Almanya'da sosyal güvenliği sağlayan önlemi sormaktadır. Doğru cevap 'Sağlık Sigortası'dır.",
    "37": "Soru, eyalet hükümet başkanlarının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı'dır.",
    "38": "Soru, Almanya'nın 'Demokratik ve sosyal bir ...' olduğunu sormaktadır. Doğru cevap 'Federal Devlet'tir.",
    "39": "Soru, her eyaletin neye sahip olduğunu sormaktadır. Doğru cevap 'Kendi hükümetine'dir.",
    "40": "Soru, Milli Marş'ın hangi kelimelerle başladığını sormaktadır. Doğru cevap 'Birlik, Adalet ve Özgürlük' ile başlar.",
    "41": "Soru, demokraside neden birden fazla parti olduğunu sormaktadır. Doğru cevap 'Farklı görüşlerin temsil edilmesi için'dir.",
    "42": "Soru, Almanya'da yasaları kimin çıkardığını sormaktadır. Doğru cevap 'Parlamento'dur.",
    "43": "Soru, bir partinin ne zaman kapatılabileceğini sormaktadır. Doğru cevap 'Anayasaya karşı mücadele ettiğinde'dir.",
    "44": "Soru, halkın doğrudan seçemediği makamı sormaktadır. Doğru cevap 'Cumhurbaşkanı'dır.",
    "45": "Soru, Bakım Sigortası'nın hangi sisteme dahil olduğunu sormaktadır. Doğru cevap 'Sosyal Sigorta' sistemine dahildir.",
    "46": "Soru, Alman devletinin görevlerinden birini sormaktadır. Doğru cevap 'Okul ve yol yapımı'dır.",
    "47": "Soru, hangisinin devletin görevi olmadığını sormaktadır. Doğru cevap 'Vatandaşların tatillerini ödemek'tir.",
    "48": "Soru, hangisinin Almanya'nın anayasal organlarından biri olmadığını sormaktadır. Doğru cevap 'Vatandaş Meclisi'dir.",
    "49": "Soru, okul politikasını kimin belirlediğini sormaktadır. Doğru cevap 'Eyaletler'dir.",
    "50": "Soru, Almanya'nın ekonomik sistemini sormaktadır. Doğru cevap 'Sosyal Piyasa Ekonomisi'dir.",
    "51": "Soru, hangisinin demokratik hukuk devleti ile bağdaşmadığını sormaktadır. Doğru cevap 'Kişilerin özel polis tarafından sebepsiz tutuklanması'dır.",
    "52": "Soru, 'Halk Egemenliği'nin ne anlama geldiğini sormaktadır. Doğru cevap 'Devlet gücünün halktan kaynaklanması'dır.",
    "53": "Soru, 'Hukuk Devleti' kavramının ne anlama geldiğini sormaktadır. Doğru cevap 'Devletin yasalara uymak zorunda olması'dır.",
    "54": "Soru, hangisinin devletin güçlerinden biri olmadığını sormaktadır. Doğru cevap 'Direktif'tir.",
    "55": "Soru, resimdeki binanın ne olduğunu sormaktadır. Doğru cevap 'Berlin'deki Federal Meclis Binası'dır.",
    "56": "Soru, hangisinin belediye yönetimine ait bir daire olduğunu sormaktadır. Doğru cevap 'Düzen Dairesi'dir (Ordnungsamt).",
    "57": "Soru, kimin Federal Meclis Başkanı seçildiğini sormaktadır. Doğru cevap 'Genellikle en büyük partinin bir milletvekilidir'.",
    "58": "Soru, Federal Bakanları kimin atadığını sormaktadır. Doğru cevap 'Cumhurbaşkanı'dır.",
    "59": "Soru, Almanya topraklarında ilk Yahudi cemaatinin ne kadar önce kurulduğunu sormaktadır. Doğru cevap 'Yaklaşık 1700 yıl önce'dir.",
    "60": "Soru, Meclislerin hangi güce ait olduğunu sormaktadır. Doğru cevap 'Yasama Gücü'dür.",
    "61": "Soru, 'Halk Egemenliği'nin ne anlama geldiğini sormaktadır. Doğru cevap 'Devlet gücünün halktan kaynaklanması'dır.",
    "62": "Soru, bir eyalet parlamentosu seçimine ne dendiğini sormaktadır. Doğru cevap 'Eyalet Meclisi Seçimi'dir.",
    "63": "Soru, hangisinin Yürütme Gücü'ne ait olmadığını sormaktadır. Doğru cevap 'Mahkemeler'dir.",
    "64": "Soru, Federal Almanya'nın idari yapısını sormaktadır. Doğru cevap 'Federasyon, Eyaletler ve Belediyeler'dir.",
    "65": "Soru, hangisinin Federal Meclis'in görevi olmadığını sormaktadır. Doğru cevap 'Kabineyi oluşturmak'tır.",
    "66": "Soru, en büyük Yahudi cemaatlerinin hangi şehirlerde olduğunu sormaktadır. Doğru cevap 'Berlin ve Münih'tir.",
    "67": "Soru, eyaletlerin temel görevini sormaktadır. Doğru cevap 'Okul politikası'dır.",
    "68": "Soru, devletin okulları neden denetlediğini sormaktadır. Doğru cevap 'Anayasa'daki görevi olduğu için'dir.",
    "69": "Soru, üç aşamalı idari yapının en alt basamağını sormaktadır. Doğru cevap 'Belediyeler'dir.",
    "70": "Soru, Cumhurbaşkanı'nın görevlerinden birini sormaktadır. Doğru cevap 'Başbakanı seçilmesi için Meclis'e önermek'tir.",
    "71": "Soru, Başbakan'ın mesaisini çoğunlukla nerede geçirdiğini sormaktadır. Doğru cevap 'Berlin'de'dir.",
    "72": "Soru, şu anki Almanya Başbakanı'nın adını sormaktadır. Doğru cevap 'Friedrich Merz'dir.",
    "73": "Soru, şu anki en büyük iki meclis grubunu sormaktadır. Doğru cevap 'CDU/CSU ve AfD'dir.",
    "74": "Soru, tüm Almanya'yı temsil eden parlamentoyu sormaktadır. Doğru cevap 'Bundestag'dır.",
    "75": "Soru, şu anki Devlet Başkanı'nı sormaktadır. Doğru cevap 'Frank-Walter Steinmeier'dir.",
    "76": "Soru, CDU kısaltmasının açılımını sormaktadır. Doğru cevap 'Hristiyan Demokrat Birliği'dir.",
    "77": "Soru, 'Bundeswehr'in ne olduğunu sormaktadır. Doğru cevap 'Alman Ordusu'dur.",
    "78": "Soru, SPD kısaltmasının açılımını sormaktadır. Doğru cevap 'Almanya Sosyal Demokrat Partisi'dir.",
    "79": "Soru, FDP kısaltmasının açılımını sormaktadır. Doğru cevap 'Hür Demokrat Parti'dir.",
    "80": "Soru, Anayasa'yı yorumlayan mahkemeyi sormaktadır. Doğru cevap 'Federal Anayasa Mahkemesi'dir.",
    "81": "Soru, Başbakanı kimin seçtiğini sormaktadır. Doğru cevap 'Federal Meclis'tir.",
    "82": "Soru, Bakanlar Kurulu'nu kimin yönettiğini sormaktadır. Doğru cevap 'Başbakan'dır.",
    "83": "Soru, Başbakanı kimin seçtiğini sormaktadır. Doğru cevap 'Bundestag'dır.",
    "84": "Soru, Cumhurbaşkanı'nın temel görevini sormaktadır. Doğru cevap 'Ülkeyi temsil etmek'tir.",
    "85": "Soru, Bundesrat'ı kimlerin oluşturduğunu sormaktadır. Doğru cevap 'Eyalet hükümetlerinin temsilcileri'dir.",
    "86": "Soru, Cumhurbaşkanı'nı kimin seçtiğini sormaktadır. Doğru cevap 'Bundesversammlung'dur.",
    "87": "Soru, Almanya'nın devlet başkanını sormaktadır. Doğru cevap 'Cumhurbaşkanı'dır.",
    "88": "Soru, muhalefetin görevini sormaktadır. Doğru cevap 'Hükümeti denetlemek'tir.",
    "89": "Soru, aynı partiden milletvekillerinin oluşturduğu gruba ne dendiğini sormaktadır. Doğru cevap 'Meclis Grubu'dur.",
    "90": "Soru, eyaletlerin federal yasalara nasıl katıldığını sormaktadır. Doğru cevap 'Bundesrat aracılığıyla'dır.",
    "91": "Soru, eyalet seçimlerinin federal politikayı nasıl etkileyebileceğini sormaktadır. Doğru cevap 'Bundesrat'taki çoğunluk değişebileceğinden'dir.",
    "92": "Soru, CSU kısaltmasının açılımını sormaktadır. Doğru cevap 'Hristiyan Sosyal Birliği'dir.",
    "93": "Soru, genel seçimlerde 'İkinci Oy'un önemini sormaktadır. Doğru cevap 'Partinin meclisteki sandalye sayısını belirler'dir.",
    "94": "Soru, genel seçimlerde oy kullanma yaşını sormaktadır. Doğru cevap '18'dir.",
    "95": "Soru, çocuklar için neyin geçerli olduğunu sormaktadır. Doğru cevap 'Zorunlu Eğitim'dir.",
    "96": "Soru, Holokost'u inkar etmenin cezasını sormaktadır. Doğru cevap 'Hapis veya para cezası'dır.",
    "97": "Soru, çalışanların maaşından otomatik kesilen ödemeyi sormaktadır. Doğru cevap 'Sosyal Sigorta'dır.",
    "98": "Soru, milletvekilleri parti değiştirirse ne olabileceğini sormaktadır. Doğru cevap 'Hükümet çoğunluğunu kaybedebilir' şeklindedir.",
    "99": "Soru, sosyal sigortaları kimin ödediğini sormaktadır. Doğru cevap 'İşveren ve işçi'dir.",
    "100": "Soru, hangisinin zorunlu sosyal sigorta olmadığını sormaktadır. Doğru cevap 'Hayat Sigortası'dır.",
  


    "101": "Soru, Sendikaların kimin çıkarlarını savunduğunu sormaktadır. Doğru cevap 'İşçilerin (Çalışanların)'dır.",
    "102": "Soru, Almanya'da üstün başarı gösterenlere verilen nişanı sormaktadır. Doğru cevap 'Federal Liyakat Nişanı'dır (Bundesverdienstkreuz).",
    "103": "Soru, 'Trafik Lambası Koalisyonu'nun (Ampel) hangi partilerden oluştuğunu sormaktadır. Doğru cevap 'SPD, FDP ve Yeşiller'dir.",
    "104": "Soru, bir kadının işten çıkarılma sebebi olamayacak durumu sormaktadır. Doğru cevap 'Hamile olması'dır.",
    "105": "Soru, seçim görevlilerinin bir görevini sormaktadır. Doğru cevap 'Oyları saymak'tır.",
    "106": "Soru, seçim görevlilerinin ne yaptığını sormaktadır. Doğru cevap 'Seçimden sonra oyları sayarlar' şeklindedir.",
    "107": "Soru, Federal Meclis'in kaç yıllığına seçildiğini sormaktadır. Doğru cevap '4 yıl'dır.",
    "108": "Soru, kimlerin genel seçimlerde oy kullanabildiğini sormaktadır. Doğru cevap 'Alman vatandaşı ve 18 yaşını doldurmuş olanlar'dır.",
    "109": "Soru, genel seçimlerin ne sıklıkla yapıldığını sormaktadır. Doğru cevap '4 yılda bir'dir.",
    "110": "Soru, Federal Meclis'in görev süresini sormaktadır. Doğru cevap '4 yıl'dır.",
    "111": "Soru, İsrail ile ilgili yasak olan eylemi sormaktadır. Doğru cevap 'İsrail'in yok edilmesi çağrısı yapmak'tır.",
    "112": "Soru, seçimlerin özelliklerinden birini sormaktadır. Doğru cevap 'Gizli olmasıdır' (geheim).",
    "113": "Soru, seçimleri hangi partinin kazandığını sormaktadır. Doğru cevap 'En çok oyu alan parti'dir.",
    "114": "Soru, demokratik seçimlere katılmanın ne olduğunu sormaktadır. Doğru cevap 'Bir haktır'.",
    "115": "Soru, 'Aktif Seçme Hakkı'nın ne anlama geldiğini sormaktadır. Doğru cevap 'Kişinin oy kullanabilmesi'dir.",
    "116": "Soru, oy kullanabilme hakkına ne isim verildiğini sormaktadır. Doğru cevap 'Aktif Seçme Hakkı'dır.",
    "117": "Soru, meclise girmek için gereken barajı sormaktadır. Doğru cevap '%5'tir.",
    "118": "Soru, Makkabi spor kulüplerine kimlerin üye olabileceğini sormaktadır. Doğru cevap 'Herkes'tir.",
    "119": "Soru, 'Özgür Seçim'in ne anlama geldiğini sormaktadır. Doğru cevap 'Kişinin baskı olmadan karar verebilmesi'dir.",
    "120": "Soru, Almanya'daki seçim sistemini sormaktadır. Doğru cevap 'Çoğunluk ve Nispi Temsil Sistemi karışımı'dır.",
    "121": "Soru, meclise girmek için gereken asgari oy oranına ne dendiğini sormaktadır. Doğru cevap '%5 Barajı'dır.",
    "122": "Soru, seçim ilkelerini sormaktadır. Doğru cevap 'Özgür, eşit ve gizli'dir.",
    "123": "Soru, %5 Barajı'nın ne olduğunu sormaktadır. Doğru cevap 'Parlamentoya girmek için gereken asgari oy oranı'dır.",
    "124": "Soru, genel seçimlerde neyin seçildiğini sormaktadır. Doğru cevap 'Almanya Parlamentosu (Bundestag)'dur.",
    "125": "Soru, düzenli seçimlerin işlevini sormaktadır. Doğru cevap 'Halkın isteğiyle hükümet değişimini sağlamak'tır.",
    "126": "Soru, seçimden önce seçmenlere ne gönderildiğini sormaktadır. Doğru cevap 'Seçim Bildirimi'dir.",
    "127": "Soru, %5 Barajı'nın neden olduğunu sormaktadır. Doğru cevap 'Çok sayıda küçük partinin hükümet kurmayı zorlaştırmasını engellemek için'dir.",
    "128": "Soru, halk tarafından seçilen meclis üyelerine ne dendiğini sormaktadır. Doğru cevap 'Milletvekili'dir.",
    "129": "Soru, halk tarafından doğrudan seçilen organı sormaktadır. Doğru cevap 'Federal Meclis (Bundestag)'tir.",
    "130": "Soru, geçerli oy pusulasını sormaktadır. Doğru cevap 'Bild 1' (Genellikle açık ve net işaretlenmiş olan).",
    "131": "Soru, Belediye Başkanı'nın kim olduğunu sormaktadır. Doğru cevap 'Belediyenin başı'dır.",
    "132": "Soru, 'Gönüllü Çalışma'nın (Ehrenamt) ne anlama geldiğini sormaktadır. Doğru cevap 'Gönüllü ve ücretsiz çalışmak'tır.",
    "133": "Soru, seçimlerde neyin serbest olduğunu sormaktadır. Doğru cevap 'Mektupla oy kullanmak'tır.",
    "134": "Soru, yerel bir sorunu çözmek için (örn. otobüs hattı) ne yapılabileceğini sormaktadır. Doğru cevap 'Vatandaş İnisiyatifi kurmak'tır.",
    "135": "Soru, sendikaların kimi temsil ettiğini sormaktadır. Doğru cevap 'İşçileri (Çalışanları)'dır.",
    "136": "Soru, ne zaman İş Mahkemesi'ne gidileceğini sormaktadır. Doğru cevap 'Haksız yere işten çıkarılma durumunda'dır.",
    "137": "Soru, işyeri anlaşmazlıklarında hangi mahkemenin yetkili olduğunu sormaktadır. Doğru cevap 'İş Mahkemesi'dir.",
    "138": "Soru, haksız işten çıkarmada ne yapılabileceğini sormaktadır. Doğru cevap 'İşe İade Davası açmak'tır.",
    "139": "Soru, ne zaman mahkeme süreci başladığını sormaktadır. Doğru cevap 'Bir suç işlendiğinde ve dava açıldığında'dır.",
    "140": "Soru, 'Schöffe'nin (Fahri Hakim) ne yaptığını sormaktadır. Doğru cevap 'Hakimle birlikte suç ve ceza konusunda karar verir' şeklindedir.",
    "141": "Soru, hukuki konularda kimin danışmanlık yaptığını sormaktadır. Doğru cevap 'Avukat'tır.",
    "142": "Soru, hakimin ana görevini sormaktadır. Doğru cevap 'Adalet dağıtmak ve hüküm vermektir'.",
    "143": "Soru, hakimin hangi güce bağlı olduğunu sormaktadır. Doğru cevap 'Yargı Gücü'dür.",
    "144": "Soru, hakimin hangi erke ait olduğunu sormaktadır. Doğru cevap 'Yargı Erki'dir.",
    "145": "Soru, hakimin kimin adına çalıştığını sormaktadır. Doğru cevap 'Yargı Gücü'dür.",
    "146": "Soru, mahkeme sürecine ne dendiğini sormaktadır. Doğru cevap 'Dava/Duruşma'dır.",
    "147": "Soru, hakimin ne iş yaptığını sormaktadır. Doğru cevap 'Hüküm vermektir'.",
    "148": "Soru, polisin görevini sormaktadır. Doğru cevap 'Yasaların uygulanmasını denetlemek'tir.",
    "149": "Soru, Yahudi düşmanlığına (antisemitizm) bir örnek sormaktadır. Doğru cevap 'Holokost'u inkar etmek'tir.",
    "150": "Soru, 'Schöffe'nin ne olduğunu sormaktadır. Doğru cevap 'Fahri (Gönüllü) Hakim'dir.",
    "151": "Soru, Berlin Duvarı'nı kimin inşa ettiğini sormaktadır. Doğru cevap 'Doğu Almanya (DDR)'dır.",
    "152": "Soru, Nazilerin ne zaman iktidarda olduğunu sormaktadır. Doğru cevap '1933-1945 arası'dır.",
    "153": "Soru, 8 Mayıs 1945'in önemini sormaktadır. Doğru cevap 'Avrupa'da İkinci Dünya Savaşı'nın sonu'dur.",
    "154": "Soru, İkinci Dünya Savaşı'nın ne zaman bittiğini sormaktadır. Doğru cevap '1945'tir.",
    "155": "Soru, Nazilerin iktidar dönemini sormaktadır. Doğru cevap '1933-1945'tir.",
    "156": "Soru, Hitler'in ne zaman Şansölye olduğunu sormaktadır. Doğru cevap '1933'tür.",
    "157": "Soru, Nazilerin 1933'te ne kurduğunu sormaktadır. Doğru cevap 'Diktatörlük'tür.",
    "158": "Soru, 'Üçüncü İmparatorluk'un ne olduğunu sormaktadır. Doğru cevap 'Bir diktatörlüktü' şeklindedir.",
    "159": "Soru, Nazi Almanyasında neyin olmadığını sormaktadır. Doğru cevap 'Özgür seçimler'dir.",
    "160": "Soru, 1939-1945 arası süren savaşı sormaktadır. Doğru cevap 'İkinci Dünya Savaşı'dır.",
    "161": "Soru, Nazi devletinin politikasını sormaktadır. Doğru cevap 'Devlet ırkçılığı'dır.",
    "162": "Soru, Stauffenberg'in neyle tanındığını sormaktadır. Doğru cevap 'Hitler'e suikast girişimi (1944)'dir.",
    "163": "Soru, sinagogların ne zaman yakıldığını sormaktadır. Doğru cevap '1938'dir.",
    "164": "Soru, 9 Kasım 1938'de ne olduğunu sormaktadır. Doğru cevap 'Yahudi işyerleri ve sinagogların tahrip edilmesi'dir.",
    "165": "Soru, Federal Almanya'nın ilk başbakanını sormaktadır. Doğru cevap 'Konrad Adenauer'dir.",
    "166": "Soru, 'Biz halkız' sloganının nerede kullanıldığını sormaktadır. Doğru cevap 'DDR (Doğu Almanya) gösterilerinde (1989)'dir.",
    "167": "Soru, İkinci Dünya Savaşı sonrası işgal güçlerini sormaktadır. Doğru cevap 'ABD, Sovyetler, İngiltere, Fransa'dır.",
    "168": "Soru, hangisinin işgal gücü olmadığını sormaktadır. Doğru cevap 'Japonya'dır.",
    "169": "Soru, Federal Almanya'nın kuruluş yılını sormaktadır. Doğru cevap '1949'dur.",
    "170": "Soru, Nazi döneminde neyin olduğunu sormaktadır. Doğru cevap 'Partilerin yasaklanması'dır.",
    "171": "Soru, Sosyal Piyasa Ekonomisi'nin anlamını sormaktadır. Doğru cevap 'Piyasa ekonomisi ve sosyal dengenin birleşimi'dir.",
    "172": "Soru, Doğu Almanya'nın hangi işgal bölgesinde kurulduğunu sormaktadır. Doğru cevap 'Sovyet Bölgesi'nde'dir.",
    "173": "Soru, Federal Almanya'nın kurucu üyesi olduğu birliği sormaktadır. Doğru cevap 'Avrupa Birliği'dir.",
    "174": "Soru, Doğu Almanya'nın (DDR) kuruluş yılını sormaktadır. Doğru cevap '1949'dur.",
    "175": "Soru, kaç işgal bölgesi olduğunu sormaktadır. Doğru cevap '4'tür.",
    "176": "Soru, haritadaki işgal bölgelerini sormaktadır. Doğru cevap 'Farklı renklerle gösterilen 4 bölge (ABD, İngiltere, Fransa, Sovyetler)'dir.",
    "177": "Soru, 4 sektöre bölünen şehri sormaktadır. Doğru cevap 'Berlin'dir.",
    "178": "Soru, Berlin Hava Köprüsü'nün nedenini sormaktadır. Doğru cevap 'Sovyetlerin yolları kapatması (Abluka)'dır.",
    "179": "Soru, savaşın resmen nasıl bittiğini sormaktadır. Doğru cevap 'Almanya'nın kayıtsız şartsız teslim olmasıyla'dır.",
    "180": "Soru, ilk başbakanı sormaktadır. Doğru cevap 'Konrad Adenauer'dir.",
    "181": "Soru, Willy Brandt'ın Varşova'daki diz çöküşünün anlamını sormaktadır. Doğru cevap 'Polonya ve Yahudilerden özür dilemesi'dir.",
    "182": "Soru, Yahudi ibadethanesinin adını sormaktadır. Doğru cevap 'Sinagog'dur.",
    "183": "Soru, Ekonomik Mucize'nin (Wirtschaftswunder) ne zaman olduğunu sormaktadır. Doğru cevap '1950'ler'dir.",
    "184": "Soru, İsrail devletinin kuruluş dayanağını sormaktadır. Doğru cevap 'Birleşmiş Milletler kararı'dır.",
    "185": "Soru, 'Demir Perde'nin neyi ifade ettiğini sormaktadır. Doğru cevap 'Doğu ve Batı blokları arasındaki bölünmeyi'dir.",
    "186": "Soru, 1953 Doğu Almanya ayaklanmasının tarihini sormaktadır. Doğru cevap '17 Haziran'dır.",
    "187": "Soru, çekiç ve pergel amblemli bayrağın kime ait olduğunu sormaktadır. Doğru cevap 'Doğu Almanya (DDR)'dır.",
    "188": "Soru, Berlin Duvarı'nın inşa yılını sormaktadır. Doğru cevap '1961'dir.",
    "189": "Soru, Duvarın ne zaman yapıldığını sormaktadır. Doğru cevap '1961'dir.",
    "190": "Soru, DDR kısaltmasının açılımını sormaktadır. Doğru cevap 'Alman Demokratik Cumhuriyeti'dir.",
    "191": "Soru, Duvarın ne zaman açıldığını sormaktadır. Doğru cevap '1989'dur.",
    "192": "Soru, eski Doğu Almanya toprağı olan eyaleti sormaktadır. Doğru cevap 'Brandenburg'dur.",
    "193": "Soru, Berlin'in o tarihlerdeki durumunu sormaktadır. Doğru cevap 'Duvarla bölünmüştü' şeklindedir.",
    "194": "Soru, 3 Ekim'de neyin kutlandığını sormaktadır. Doğru cevap 'Alman Birliği'dir.",
    "195": "Soru, eski DDR eyaletini sormaktadır. Doğru cevap 'Saksonya-Anhalt'tır.",
    "196": "Soru, 'Dönüşüm' (Die Wende) döneminin anlamını sormaktadır. Doğru cevap 'Barışçıl devrimle diktatörlükten demokrasiye geçiş'tir.",
    "197": "Soru, eski DDR eyaletini sormaktadır. Doğru cevap 'Thüringen'dir.",
    "198": "Soru, eski DDR eyaletini sormaktadır. Doğru cevap 'Saksonya'dır.",
    "199": "Soru, Stasi'nin ne olduğunu sormaktadır. Doğru cevap 'Devlet Güvenlik Bakanlığı (Gizli Polis)'dır.",
    "200": "Soru, eski DDR eyaletini sormaktadır. Doğru cevap 'Mecklenburg-Vorpommern'dir.",

    "201": "Soru, hangi eyaletlerin eski Doğu Almanya toprağı olduğunu sormaktadır. Doğru cevap 'Mecklenburg-Vorpommern, Brandenburg, Saksonya, Saksonya-Anhalt, Thüringen'dir.",
    "202": "Soru, Doğu Almanya'nın Soğuk Savaş'ta kime ait olduğunu sormaktadır. Doğru cevap 'Varşova Paktı'na'dır.",
    "203": "Soru, Doğu Almanya'nın ekonomik sistemini sormaktadır. Doğru cevap 'Planlı Ekonomi'dir.",
    "204": "Soru, iki Almanya'nın nasıl birleştiğini sormaktadır. Doğru cevap 'Doğudaki 5 eyaletin Federal Almanya'ya katılmasıyla'dır.",
    "205": "Soru, yeni eyaletlerin birleşmeyle nereye katıldığını sormaktadır. Doğru cevap 'Avrupa Birliği'ne'dir.",
    "206": "Soru, 'Tökezleme Taşları'nın (Stolpersteine) neyi hatırlattığını sormaktadır. Doğru cevap 'Nazi kurbanlarını'dır.",
    "207": "Soru, Doğu Almanya'nın askeri ittifakını sormaktadır. Doğru cevap 'Varşova Paktı'dır.",
    "208": "Soru, Stasi'nin ne olduğunu sormaktadır. Doğru cevap 'Doğu Almanya Gizli Servisi'dir.",
    "209": "Soru, Doğu Almanya'nın armasını sormaktadır. Doğru cevap 'Çekiç ve Pergelli arma'dır (Bild 4).",
    "210": "Soru, 17 Haziran 1953 olayını sormaktadır. Doğru cevap 'Ülke çapında grevler ve halk ayaklanması'dır.",
    "211": "Soru, 'Doğu Anlaşmaları' (Ostverträge) ile bilinen siyasetçiyi sormaktadır. Doğru cevap 'Willy Brandt'tır.",
    "212": "Soru, Almanya'nın tam adını sormaktadır. Doğru cevap 'Federal Almanya Cumhuriyeti'dir.",
    "213": "Soru, Almanya'nın nüfusunu sormaktadır. Doğru cevap 'Yaklaşık 84 milyon'dur.",
    "214": "Soru, Alman bayrağının renklerini sormaktadır. Doğru cevap 'Siyah-Kırmızı-Altın'dır.",
    "215": "Soru, 'Birliğin Şansölyesi' olarak bilinen kişiyi sormaktadır. Doğru cevap 'Helmut Kohl'dür.",
    "216": "Soru, Meclis salonundaki sembolü sormaktadır. Doğru cevap 'Federal Kartal'dır (Bundesadler).",
    "217": "Soru, Doğu Almanya'nın var olduğu tarih aralığını sormaktadır. Doğru cevap '1949-1990 arası'dır.",
    "218": "Soru, birleşmeyle kaç yeni eyaletin katıldığını sormaktadır. Doğru cevap '5'tir.",
    "219": "Soru, bugünkü sınırların ne zamandan beri geçerli olduğunu sormaktadır. Doğru cevap '1990'dan beri'dir.",
    "220": "Soru, 27 Ocak anma gününün anlamını sormaktadır. Doğru cevap 'Nazi kurbanlarını anma günü (Auschwitz'in kurtuluşu)'dur.",
    "221": "Soru, Schengen Anlaşması'nın anlamını sormaktadır. Doğru cevap 'Pasaport kontrolü olmadan seyahat edebilmek'tir.",
    "222": "Soru, Almanya'nın komşusunu sormaktadır. Doğru cevap 'İsviçre'dir.",
    "223": "Soru, Almanya'nın komşusunu sormaktadır. Doğru cevap 'Polonya'dır.",
    "224": "Soru, AB (EU) kısaltmasının anlamını sormaktadır. Doğru cevap 'Avrupa Birliği'dir.",
    "225": "Soru, Almanca konuşulan diğer ülkeyi sormaktadır. Doğru cevap 'Avusturya'dır.",
    "226": "Soru, AB bayrağını sormaktadır. Doğru cevap 'Mavi zemin üzerine sarı yıldızlar'dır (Bild 2).",
    "227": "Soru, Almanya'nın komşusunu sormaktadır. Doğru cevap 'Danimarka'dır.",
    "228": "Soru, Doğu Almanya'nın katılımına ne dendiğini sormaktadır. Doğru cevap 'Alman Yeniden Birleşmesi'dir.",
    "229": "Soru, Almanya'nın komşusunu sormaktadır. Doğru cevap 'Lüksemburg'dur.",
    "230": "Soru, Avrupa Parlamentosu seçimlerinin ne sıklıkla yapıldığını sormaktadır. Doğru cevap '5 yılda bir'dir.",
    "231": "Soru, 'Avrupa Entegrasyonu'nun ne anlama geldiğini sormaktadır. Doğru cevap 'Avrupa devletlerinin AB çatısı altında birleşmesi'dir.",
    "232": "Soru, Avrupa seçimlerinde kimin seçildiğini sormaktadır. Doğru cevap 'Avrupa Parlamentosu Milletvekilleri'dir.",
    "233": "Soru, Almanya'nın komşusunu sormaktadır. Doğru cevap 'Çekya'dır.",
    "234": "Soru, Avrupa Parlamentosu'nun merkezini sormaktadır. Doğru cevap 'Strazburg'dur.",
    "235": "Soru, Mitterrand ve Kohl'ün Verdun anmasının neyi simgelediğini sormaktadır. Doğru cevap 'Barış ve güvenliği'dir.",
    "236": "Soru, AB üye sayısını sormaktadır. Doğru cevap '27'dir.",
    "237": "Soru, Roma Anlaşmaları'nın içeriğini sormaktadır. Doğru cevap 'Avrupa Ekonomik Topluluğu'nun (AET) kurulması'dır.",
    "238": "Soru, Avrupa Parlamentosu'nun çalışma yerlerini sormaktadır. Doğru cevap 'Strazburg, Lüksemburg ve Brüksel'dir.",
    "239": "Soru, Almanya'nın AET'ye hangi antlaşmayla katıldığını sormaktadır. Doğru cevap 'Roma Antlaşmaları'yla'dır.",
    "240": "Soru, Euro'nun ne zaman nakit olarak kullanılmaya başlandığını sormaktadır. Doğru cevap '2002'dir.",
    "241": "Soru, Ebeveyn Parası (Elterngeld) almak için ne yapılması gerektiğini sormaktadır. Doğru cevap 'Başvuru yapmak gerekir'dir.",
    "242": "Soru, çocuğun anaokuluna gidip gitmeyeceğine kimin karar verdiğini sormaktadır. Doğru cevap 'Ebeveynler'dir.",
    "243": "Soru, gösteri/yürüyüş yapmak için ne gerektiğini sormaktadır. Doğru cevap 'Yetkili makama bildirmek (anmelden)'tir.",
    "244": "Soru, üniversiteye girmek için gereken diplomayı sormaktadır. Doğru cevap 'Lise Diploması (Abitur)'dır.",
    "245": "Soru, kimlerin çift olarak yaşamasının yasak olduğunu sormaktadır. Doğru cevap 'Reşit olmayan (13) biriyle yetişkin (25) birinin'dir.",
    "246": "Soru, reşit olma yaşını sormaktadır. Doğru cevap '18'dir.",
    "247": "Soru, hamile kadınlar için yasal korumanın adını sormaktadır. Doğru cevap 'Annelik Koruması (Mutterschutz)'dır.",
    "248": "Soru, çocuk yetiştirmenin öncelikle kimin görevi olduğunu sormaktadır. Doğru cevap 'Ailelerin (Ebeveynlerin)'dir.",
    "249": "Soru, çocuk eğitiminden kimin sorumlu olduğunu sormaktadır. Doğru cevap 'Ebeveynler'dir.",
    "250": "Soru, iyi bir iş bulma şansını neyin artırdığını sormaktadır. Doğru cevap 'İyi bir eğitim'dir.",
    "251": "Soru, çocuğa şiddet uygulamanın sonucunu sormaktadır. Doğru cevap 'Cezalandırılabilir (Yasaktır)' şeklindedir.",
    "252": "Soru, evlilikle ilgili kuralı sormaktadır. Doğru cevap 'Sadece bir kişiyle evli olunabilir (Tek eşlilik)'dir.",
    "253": "Soru, taşınırken nereye bildirim yapıldığını sormaktadır. Doğru cevap 'Nüfus Dairesi'ne (Einwohnermeldeamt)'dir.",
    "254": "Soru, 'Ayrılık Yılı'nın (Trennungsjahr) ne anlama geldiğini sormaktadır. Doğru cevap 'Boşanmadan önce en az 1 yıl ayrı yaşamak'tır.",
    "255": "Soru, çocuk yetiştirme sorunlarında kimden yardım alınabileceğini sormaktadır. Doğru cevap 'Gençlik Dairesi (Jugendamt)'nden'dir.",
    "256": "Soru, restoran açmak için ne gerektiğini sormaktadır. Doğru cevap 'Resmi izin (Gaststättenerlaubnis)'dir.",
    "257": "Soru, yetişkinlerin liseyi nerede bitirebileceğini sormaktadır. Doğru cevap 'Akşam Lisesi'nde (Abendgymnasium)'dir.",
    "258": "Soru, Gençlik Dairesi'nin yetkisini sormaktadır. Doğru cevap 'Şiddet gören veya aç bırakılan çocuğu aileden almak'tır.",
    "259": "Soru, Meslek Bilgi Merkezi'nin (BiZ) neye yardım ettiğini sormaktadır. Doğru cevap 'Meslek yeri aramaya'dır.",
    "260": "Soru, okuldaki zorunluluğu sormaktadır. Doğru cevap 'Devam zorunluluğu (Anwesenheitspflicht)'dur.",
    "261": "Soru, 30 yaşında lise diploması almak isteyenin nereye gideceğini sormaktadır. Doğru cevap 'Akşam Lisesi'ne'dir.",
    "262": "Soru, eşitlik ilkesinin ne anlama geldiğini sormaktadır. Doğru cevap 'Kimsenin (örneğin engelli diye) dışlanmaması'dır.",
    "263": "Soru, cezai ehliyet yaşını (14) sormaktadır. Doğru cevap '14 yaşından itibaren suç işleyenler cezalandırılır'dır.",
    "264": "Soru, kostüm giyilen festivali sormaktadır. Doğru cevap 'Karnaval (Rosenmontag)'dır.",
    "265": "Soru, evlenmek için nereye gidilmesi gerektiğini sormaktadır. Doğru cevap 'Evlendirme Dairesi (Standesamt)'ne'dir.",
    "266": "Soru, yasal sessizlik saatinin (Nachtruhe) ne zaman başladığını sormaktadır. Doğru cevap 'Saat 22:00'de'dir.",
    "267": "Soru, reşit bir kızın arkadaş seçiminde ailenin ne yapması gerektiğini sormaktadır. Doğru cevap 'Kararına saygı duymalıdırlar'dır.",
    "268": "Soru, ehliyet sınavının dilini sormaktadır. Doğru cevap 'Pek çok dilde yapılabilir'dir.",
    "269": "Soru, anaokulu hakkının kaç yaşında başladığını sormaktadır. Doğru cevap '3 yaşından itibaren'dir.",
    "270": "Soru, Halk Eğitim Merkezi'nin (VHS) amacını sormaktadır. Doğru cevap 'Yetişkin eğitimi (Weiterbildung)'dir.",
    "271": "Soru, Noel geleneğini sormaktadır. Doğru cevap 'Çam ağacı süslemek'tir.",
    "272": "Soru, Almanya'da yasak olan yaşam biçimini sormaktadır. Doğru cevap 'Aynı anda iki kişiyle evli olmak'tır.",
    "273": "Soru, eğitim sorunlarında nereye gidileceğini sormaktadır. Doğru cevap 'Gençlik Dairesi'ne'dir.",
    "274": "Soru, başkasının mektubunu açmanın neyi ihlal ettiğini sormaktadır. Doğru cevap 'Haberleşme Gizliliği'ni (Briefgeheimnis)'dir.",
    "275": "Soru, boşanma için neyin şart olduğunu sormaktadır. Doğru cevap 'Bir avukatın desteği'dir.",
    "276": "Soru, resmi dairede kötü muamele görülürse ne yapılabileceğini sormaktadır. Doğru cevap 'Daire müdürüne şikayet etmek'tir.",
    "277": "Soru, kadınlara yönelik ayrımcılık örneğini sormaktadır. Doğru cevap 'Sırf anne olduğu için işe alınmamak'tır.",
    "278": "Soru, engellilere yönelik ayrımcılık örneğini sormaktadır. Doğru cevap 'Sırf tekerlekli sandalyede olduğu için işe alınmamak'tır.",
    "279": "Soru, Apartman Yönetmeliği'nde (Hausordnung) ne yazdığını sormaktadır. Doğru cevap 'Sakinlerin uyması gereken kurallar'dır.",
    "280": "Soru, hatalı vergi bildirimine karşı ne yapılacağını sormaktadır. Doğru cevap 'İtiraz etmek (Einspruch)'tir.",
    "281": "Soru, havuza alınmayan yabancıların hangi hakkının çiğnendiğini sormaktadır. Doğru cevap 'Eşit Muamele Hakkı'nın'dır.",
    "282": "Soru, vatandaşların yapmak zorunda olduğu gönüllü görevi sormaktadır. Doğru cevap 'Seçim Görevlisi olmak'tır (çağrılırsa).",
    "283": "Soru, resmi daireden yanlış fatura gelirse ne yapılacağını sormaktadır. Doğru cevap 'İtiraz etmek (Widerspruch)'tir.",
    "284": "Soru, iş dünyasındaki değişimlere karşı ne yapılması gerektiğini sormaktadır. Doğru cevap 'Sürekli eğitim almaya devam etmek'tir.",
    "285": "Soru, çalışanın maaşından ödemediği vergiyi sormaktadır. Doğru cevap 'Katma Değer Vergisi (Umsatzsteuer)'dir.",
    "286": "Soru, işyerinde işçilere yardımcı olan örgütü sormaktadır. Doğru cevap 'İşçi Temsilciliği (Betriebsrat)'dir.",
    "287": "Soru, işten ayrılırken neye dikkat edilmesi gerektiğini sormaktadır. Doğru cevap 'İhbar süresine (Kündigungsfrist)'dir.",
    "288": "Soru, Almanya'nın İsrail'e karşı sorumluluğunun kaynağını sormaktadır. Doğru cevap 'Nazi suçları'dır.",
    "289": "Soru, ırkçılık örneğini sormaktadır. Doğru cevap 'Ten rengi nedeniyle işe alınmamak'tır.",
    "290": "Soru, bozuk çıkan ürün için ne yapılabileceğini sormaktadır. Doğru cevap 'Reklamasyon (İade/Değişim) yapmak'tır.",
    "291": "Soru, vergi beyanında neden dinin sorulduğunu sormaktadır. Doğru cevap 'Kilise Vergisi kesilebileceği için'dir.",
    "292": "Soru, dini hoşgörünün anlamını sormaktadır. Doğru cevap 'Herkesin istediğine inanabilmesi'dir.",
    "293": "Soru, Paskalya geleneğini sormaktadır. Doğru cevap 'Yumurta boyamak'tır.",
    "294": "Soru, 'Pfingsten'in ne olduğunu sormaktadır. Doğru cevap 'Hristiyan bayramı'dır.",
    "295": "Soru, Avrupa kültürünü şekillendiren dini sormaktadır. Doğru cevap 'Hristiyanlık'tır.",
    "296": "Soru, Noel'den önceki 4 haftaya ne dendiğini sormaktadır. Doğru cevap 'Advent'tir.",
    "297": "Soru, Almanya'ya en çok göçmenin hangi ülkeden geldiğini sormaktadır. Doğru cevap 'Türkiye'dir.",
    "298": "Soru, Doğu Almanya'daki göçmenlerin kökenini sormaktadır. Doğru cevap 'Vietnam, Polonya, Mozambik'tir.",
    "299": "Soru, 50'lerde çağrılan işçilere ne dendiğini sormaktadır. Doğru cevap 'Misafir İşçi (Gastarbeiter)'dir.",
    "300": "Soru, ilk misafir işçilerin nereden geldiğini sormaktadır. Doğru cevap 'İtalya'dan'dır.",

    "301": "Soru, Baden-Württemberg eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 1)'dır.",
    "302": "Soru, hangisinin Baden-Württemberg eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Neckar-Odenwald-Kreis'tir.",
    "303": "Soru, Baden-Württemberg Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "304": "Soru, Baden-Württemberg eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "305": "Soru, Baden-Württemberg eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Siyah-Altın'dır.",
    "306": "Soru, Baden-Württemberg'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "307": "Soru, Baden-Württemberg eyaletinin başkentini sormaktadır. Doğru cevap 'Stuttgart'tır.",
    "308": "Soru, haritada Baden-Württemberg'in yerini sormaktadır. Doğru cevap '2 numaralı bölge'dir.",
    "309": "Soru, Baden-Württemberg hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "310": "Soru, Baden-Württemberg eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "311": "Soru, Bavyera (Bayern) eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 2)'dır.",
    "312": "Soru, hangisinin Bavyera eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Altötting'dir.",
    "313": "Soru, Bavyera Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "314": "Soru, Bavyera eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '18'dir.",
    "315": "Soru, Bavyera eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Beyaz-Mavi'dir.",
    "316": "Soru, Bavyera'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "317": "Soru, Bavyera eyaletinin başkentini sormaktadır. Doğru cevap 'Münih (München)'tir.",
    "318": "Soru, haritada Bavyera'nın yerini sormaktadır. Doğru cevap '4 numaralı bölge'dir.",
    "319": "Soru, Bavyera hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "320": "Soru, Bavyera eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "321": "Soru, Berlin eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 4)'dır.",
    "322": "Soru, hangisinin Berlin'in bir semti olduğunu sormaktadır. Doğru cevap 'Pankow'dur.",
    "323": "Soru, Berlin Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "324": "Soru, Berlin'de yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "325": "Soru, Berlin eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Beyaz-Kırmızı'dır.",
    "326": "Soru, Berlin'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "327": "Soru, hangi eyaletin aynı zamanda bir Şehir Devleti (Stadtstaat) olduğunu sormaktadır. Doğru cevap 'Berlin'dir.",
    "328": "Soru, haritada Berlin'in yerini sormaktadır. Doğru cevap '4 numaralı bölge'dir.",
    "329": "Soru, Berlin hükümet başkanının unvanını sormaktadır. Doğru cevap 'Yöneten Belediye Başkanı (Regierender Bürgermeister)'dır.",
    "330": "Soru, Berlin eyaletinde olmayan senatörlüğü sormaktadır. Doğru cevap 'Dışişleri Senatörü'dür.",
    "331": "Soru, Brandenburg eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 1)'dır.",
    "332": "Soru, hangisinin Brandenburg eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Prignitz'dir.",
    "333": "Soru, Brandenburg Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "334": "Soru, Brandenburg eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "335": "Soru, Brandenburg eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Kırmızı-Beyaz'dır.",
    "336": "Soru, Brandenburg'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "337": "Soru, Brandenburg eyaletinin başkentini sormaktadır. Doğru cevap 'Potsdam'dır.",
    "338": "Soru, haritada Brandenburg'un yerini sormaktadır. Doğru cevap '4 numaralı bölge'dir.",
    "339": "Soru, Brandenburg hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "340": "Soru, Brandenburg eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "341": "Soru, Bremen eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 3)'dır.",
    "342": "Soru, hangisinin Bremen'in bir semti olduğunu sormaktadır. Doğru cevap 'Hemelingen'dir.",
    "343": "Soru, Bremen Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '4 yıl'dır.",
    "344": "Soru, Bremen'de yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "345": "Soru, Bremen eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Kırmızı-Beyaz'dır.",
    "346": "Soru, Bremen'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "347": "Soru, hangi eyaletin bir Şehir Devleti olduğunu sormaktadır. Doğru cevap 'Bremen'dir.",
    "348": "Soru, haritada Bremen'in yerini sormaktadır. Doğru cevap '1 numaralı bölge'dir.",
    "349": "Soru, Bremen hükümet başkanının unvanını sormaktadır. Doğru cevap 'Senato Başkanı (Präsident des Senats)'dır.",
    "350": "Soru, Bremen eyaletinde olmayan senatörlüğü sormaktadır. Doğru cevap 'Dışişleri Senatörü'dür.",
    "351": "Soru, Hamburg eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 2)'dır.",
    "352": "Soru, hangisinin Hamburg'un bir semti olduğunu sormaktadır. Doğru cevap 'Altona'dır.",
    "353": "Soru, Hamburg Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "354": "Soru, Hamburg'da yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "355": "Soru, Hamburg eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Beyaz-Kırmızı'dır.",
    "356": "Soru, Hamburg'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "357": "Soru, hangi eyaletin bir Şehir Devleti olduğunu sormaktadır. Doğru cevap 'Hamburg'dur.",
    "358": "Soru, haritada Hamburg'un yerini sormaktadır. Doğru cevap '3 numaralı bölge'dir.",
    "359": "Soru, Hamburg hükümet başkanının unvanını sormaktadır. Doğru cevap 'Birinci Belediye Başkanı (Erster Bürgermeister)'dır.",
    "360": "Soru, Hamburg eyaletinde olmayan senatörlüğü sormaktadır. Doğru cevap 'Dışişleri Senatörü'dür.",
    "361": "Soru, Hessen eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 1)'dır.",
    "362": "Soru, hangisinin Hessen eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Main-Taunus-Kreis'tir.",
    "363": "Soru, Hessen Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "364": "Soru, Hessen eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '18'dir.",
    "365": "Soru, Hessen eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Kırmızı-Beyaz'dır.",
    "366": "Soru, Hessen'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "367": "Soru, Hessen eyaletinin başkentini sormaktadır. Doğru cevap 'Wiesbaden'dir.",
    "368": "Soru, haritada Hessen'in yerini sormaktadır. Doğru cevap '3 numaralı bölge'dir.",
    "369": "Soru, Hessen hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "370": "Soru, Hessen eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "371": "Soru, Mecklenburg-Vorpommern eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 3)'dır.",
    "372": "Soru, hangisinin Mecklenburg-Vorpommern eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Mecklenburgische Seenplatte'dır.",
    "373": "Soru, Mecklenburg-Vorpommern Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "374": "Soru, Mecklenburg-Vorpommern eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "375": "Soru, Mecklenburg-Vorpommern eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Mavi-Beyaz-Sarı-Kırmızı'dır.",
    "376": "Soru, Mecklenburg-Vorpommern'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "377": "Soru, Mecklenburg-Vorpommern eyaletinin başkentini sormaktadır. Doğru cevap 'Schwerin'dir.",
    "378": "Soru, haritada Mecklenburg-Vorpommern'in yerini sormaktadır. Doğru cevap '3 numaralı bölge'dir.",
    "379": "Soru, Mecklenburg-Vorpommern hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "380": "Soru, Mecklenburg-Vorpommern eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "381": "Soru, Aşağı Saksonya (Niedersachsen) eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 3)'dır.",
    "382": "Soru, hangisinin Aşağı Saksonya eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Ammerland'dır.",
    "383": "Soru, Aşağı Saksonya Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "384": "Soru, Aşağı Saksonya eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "385": "Soru, Aşağı Saksonya eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Siyah-Kırmızı-Altın'dır.",
    "386": "Soru, Aşağı Saksonya'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "387": "Soru, Aşağı Saksonya eyaletinin başkentini sormaktadır. Doğru cevap 'Hannover'dir.",
    "388": "Soru, haritada Aşağı Saksonya'nın yerini sormaktadır. Doğru cevap '1 numaralı bölge'dir.",
    "389": "Soru, Aşağı Saksonya hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "390": "Soru, Aşağı Saksonya eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "391": "Soru, Kuzey Ren-Vestfalya (NRW) eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 2)'dır.",
    "392": "Soru, hangisinin NRW eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Rhein-Sieg-Kreis'tir.",
    "393": "Soru, NRW Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "394": "Soru, NRW eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "395": "Soru, NRW eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Yeşil-Beyaz-Kırmızı'dır.",
    "396": "Soru, NRW'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "397": "Soru, NRW eyaletinin başkentini sormaktadır. Doğru cevap 'Düsseldorf'tur.",
    "398": "Soru, haritada NRW'nin yerini sormaktadır. Doğru cevap '3 numaralı bölge'dir.",
    "399": "Soru, NRW hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "400": "Soru, NRW eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "401": "Soru, Rheinland-Pfalz eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 1)'dır.",
    "402": "Soru, hangisinin Rheinland-Pfalz eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Westerwaldkreis'tır.",
    "403": "Soru, Rheinland-Pfalz Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "404": "Soru, Rheinland-Pfalz eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '18'dir.",
    "405": "Soru, Rheinland-Pfalz eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Siyah-Kırmızı-Altın'dır.",
    "406": "Soru, Rheinland-Pfalz'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "407": "Soru, Rheinland-Pfalz eyaletinin başkentini sormaktadır. Doğru cevap 'Mainz'dir.",
    "408": "Soru, haritada Rheinland-Pfalz'ın yerini sormaktadır. Doğru cevap '1 numaralı bölge'dir.",
    "409": "Soru, Rheinland-Pfalz hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "410": "Soru, Rheinland-Pfalz eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "411": "Soru, Saarland eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 4)'dır.",
    "412": "Soru, hangisinin Saarland eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Neunkirchen'dir.",
    "413": "Soru, Saarland Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "414": "Soru, Saarland eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '18'dir.",
    "415": "Soru, Saarland eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Siyah-Kırmızı-Altın'dır.",
    "416": "Soru, Saarland'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "417": "Soru, Saarland eyaletinin başkentini sormaktadır. Doğru cevap 'Saarbrücken'dir.",
    "418": "Soru, haritada Saarland'ın yerini sormaktadır. Doğru cevap '2 numaralı bölge'dir.",
    "419": "Soru, Saarland hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "420": "Soru, Saarland eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "421": "Soru, Saksonya (Sachsen) eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 4)'dır.",
    "422": "Soru, hangisinin Saksonya eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Vogtlandkreis'tır.",
    "423": "Soru, Saksonya Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "424": "Soru, Saksonya eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '18'dir.",
    "425": "Soru, Saksonya eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Beyaz-Yeşil'dir.",
    "426": "Soru, Saksonya'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "427": "Soru, Saksonya eyaletinin başkentini sormaktadır. Doğru cevap 'Dresden'dir.",
    "428": "Soru, haritada Saksonya'nın yerini sormaktadır. Doğru cevap '4 numaralı bölge'dir.",
    "429": "Soru, Saksonya hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "430": "Soru, Saksonya eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "431": "Soru, Saksonya-Anhalt eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 4)'dır.",
    "432": "Soru, hangisinin Saksonya-Anhalt eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Börde'dir.",
    "433": "Soru, Saksonya-Anhalt Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "434": "Soru, Saksonya-Anhalt eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "435": "Soru, Saksonya-Anhalt eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Sarı-Siyah'tır.",
    "436": "Soru, Saksonya-Anhalt'ta siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "437": "Soru, Saksonya-Anhalt eyaletinin başkentini sormaktadır. Doğru cevap 'Magdeburg'dur.",
    "438": "Soru, haritada Saksonya-Anhalt'ın yerini sormaktadır. Doğru cevap '3 numaralı bölge'dir.",
    "439": "Soru, Saksonya-Anhalt hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "440": "Soru, Saksonya-Anhalt eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "441": "Soru, Schleswig-Holstein eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 3)'dır.",
    "442": "Soru, hangisinin Schleswig-Holstein eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Nordfriesland'dır.",
    "443": "Soru, Schleswig-Holstein Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "444": "Soru, Schleswig-Holstein eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "445": "Soru, Schleswig-Holstein eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Mavi-Beyaz-Kırmızı'dır.",
    "446": "Soru, Schleswig-Holstein'da siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Sorumlusu'ndan'dir.",
    "447": "Soru, Schleswig-Holstein eyaletinin başkentini sormaktadır. Doğru cevap 'Kiel'dir.",
    "448": "Soru, haritada Schleswig-Holstein'ın yerini sormaktadır. Doğru cevap '1 numaralı bölge'dir.",
    "449": "Soru, Schleswig-Holstein hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "450": "Soru, Schleswig-Holstein eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır.",
    "451": "Soru, Thüringen eyaletinin armasını sormaktadır. Doğru cevap 'Resimdeki arma (Bild 4)'dır.",
    "452": "Soru, hangisinin Thüringen eyaletinde bir ilçe olduğunu sormaktadır. Doğru cevap 'Wartburgkreis'tır.",
    "453": "Soru, Thüringen Eyalet Meclisi'nin kaç yılda bir seçildiğini sormaktadır. Doğru cevap '5 yıl'dır.",
    "454": "Soru, Thüringen eyaletinde yerel seçim yaşını sormaktadır. Doğru cevap '16'dır.",
    "455": "Soru, Thüringen eyalet bayrağının renklerini sormaktadır. Doğru cevap 'Beyaz-Kırmızı'dır.",
    "456": "Soru, Thüringen'de siyasi bilginin nereden alınacağını sormaktadır. Doğru cevap 'Eyalet Siyasi Eğitim Merkezi'nden'dir.",
    "457": "Soru, Thüringen eyaletinin başkentini sormaktadır. Doğru cevap 'Erfurt'tur.",
    "458": "Soru, haritada Thüringen'in yerini sormaktadır. Doğru cevap '2 numaralı bölge'dir.",
    "459": "Soru, Thüringen hükümet başkanının unvanını sormaktadır. Doğru cevap 'Eyalet Başbakanı (Ministerpräsident)'dır.",
    "460": "Soru, Thüringen eyaletinde olmayan bakanlığı sormaktadır. Doğru cevap 'Dışişleri Bakanı'dır."
  };

  final File file = File('assets/data/lang/tr.json');
  const JsonEncoder encoder = JsonEncoder.withIndent('  ');
  await file.writeAsString(encoder.convert(translations));
  print('Written ${translations.length} translations with indentation.');
}
